System/job/urls.py
from django.urls import path
from .views import JobViews 

app_name="job"

urlpatterns = [
    path('', JobViews.add_job,name='add_job'),
    path('apply/<int:job_id>', JobViews.apply_job,name='apply_job'),
    path('jobs/<int:job_id>', JobViews.show_applications,name='my_jobs'),
    path('edit/<int:job_id>', JobViews.edit_job,name='edit_job'),
    path('accept/<int:application_id>', JobViews.accept_application,name='accept'),
    path('reject/<int:application_id>/', JobViews.reject_application, name='reject'),
    path('delete/<int:job_id>/', JobViews.delete_job, name='delete_job'),
]

System/job/templates/add_job.html
{% extends "layout.html" %}
{% load static %}
{% block custom_head_tag %}
<script src="{% static "js/admin.js" %}"></script>
{% endblock custom_head_tag %}

{% block title %}Add Job{% endblock title %}

{% block content %}
<div class="w-full flex flex-col items-center py-4">
    <div id="custom-popup" class="transition-all backdrop-blur-sm">
        <div class="bg-white p-6 rounded shadow-lg text-center">
            <p id="popup-message" class="mb-4"></p>
            <div class="flex justify-center gap-4">
                <button id="confirm-btn" class="w-1/2 bg-green-500 text-white px-6 py-2 rounded">Confirm</button>
                <button id="cancel-btn" class="w-1/2 bg-red-600 text-white px-6 py-2 rounded">Cancel</button>
            </div>
        </div>
    </div>
    
    <div class="fixed w-fit left-0 px-10">
        <button id="cancel-changes" class="bg-red-700 py-2 px-5 rounded-md text-white hover:bg-red-600">Go Back</button>
    </div>

    <form method="post" class="form w-2/3 bg-white px-10 py-4 border-2 rounded-md flex flex-col gap-4" enctype="multipart/form-data">
        <p></p>
        {% csrf_token %}
        {{ form.media }} 
        <div>
            <label for="title">Title</label>
            {{form.title}}
            <span class="text-xs text-red-700">{{form.errors.title}}</span>
        </div>
        <div>
            <label for="title">Location</label>
            {{form.location}}
            <span class="text-xs text-red-700">{{form.errors.location}}</span>
        </div>
        
        <div class="flex flex-col">
            <label for="title">Description</label>
            {{form.description|safe}}
            <span class="text-xs text-red-700">{{form.errors.description}}</span>
        </div>
        
        <div>
            <label for="title">Date</label>
            {{form.date|safe}}
            <span class="text-xs text-red-700">{{form.errors.date}}</span>
        </div>

        <div>
            <label for="title">Budget</label>
            {{form.budget}}
            <span class="text-xs text-red-700">{{form.errors.budget}}</span>
        </div>
        <div class="flex flex-row h-fit gap-8">
            <div>
                <label for="title" class="text-medium">Category</label>
                <div class="flex flex-col text-xs gap-2">
                    {% for field in form.category %}
                        {{field}}
                    {% endfor %}
                </div>
                <span class="text-xs text-red-700">{{form.errors.category}}</span>
            </div>
            <div>
                <label for="title">Schedule</label>
                <div class="flex flex-col text-xs gap-2">
                    {% for field in form.schedule %}
                        {{field}}
                    {% endfor %}
                </div>
                <span class="text-xs text-red-700">{{form.errors.schedule}}</span>
            </div>
            <div>
                <label for="title">Payment Method</label>
                <div class="flex flex-col text-xs gap-2">
                    {% for field in form.payment_method %}
                        {{field}}
                    {% endfor %}
                </div>
                <span class="text-xs text-red-700">{{form.errors.payment_method}}</span>
            </div>
        </div>
        <button id="post_job" class="w-full bg-green-700 text-white py-2 hover:bg-green-800" type="submit">Confirm Changes</button>
    </form>
</div>
{% endblock content %}

System/job/templates/apply_job.html
{% extends "layout.html" %}

{% load static %}
{% block custom_head_tag %}
    <script src="{% static "js/job.js" %}"></script>
{% endblock custom_head_tag %}

{% block title %}Apply {{job}}{% endblock title %}
{% block content %}
<div id="custom-popup" class="transition-all backdrop-blur-sm">
    <div class="bg-white p-6 rounded text-center">
        <p id="popup-message" class="pb-4 text-sm"></p>
        <div class="flex justify-center gap-2">
            <button id="confirm-btn" class="bg-green-500 text-white px-4 py-2 rounded text-sm">Confirm</button>
            <button id="cancel-btn" class="bg-red-600 text-white px-4 py-2 rounded text-sm">Cancel</button>
        </div>
    </div>
</div>

{% for message in messages %}
    {% if message %}
        <div id="popup" class="fixed h-5/6 w-full flex flex-row transition-all">
            <div class="bg-white w-1/4 mx-auto mt-auto p-4 border-l-4 border-green-600 shadow-custom_spread">
                <p>{{ message }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

<div class="h-screen w-screen bg-slate-100 flex flex-col md:flex-row  py-4 px-2 lg:px-28 gap-4">
    <div class="w-full md:w-2/5 flex flex-col gap-4 bg-white rounded-sm border-2  px-4 h-fit p-4">
        <div class="flex flex-row place-items-end gap-2 text-green-700 w-1/2 ">
            {% if job.employer.image %}
            <img class="w-1/2 aspect-h-1 rounded-sm self-center my-auto" src="{{job.employer.image.url}}" alt="Profile picture of {{job.employerusername}}"/>
                {% else %}
            <img class="w-1/2 aspect-h-1 rounded-sm self-center my-auto " src="{% static "/images/default.webp" %}" alt="Default Profile"/>
            {% endif %}
            <a href="{% url 'profile:profile' job.employer.username %}" class=" self-center text-lg font-bold hover:text-green-900">{{job.employer}}</a>
        </div>
        <div class="flex flex-col gap-2">
            <p class="text-green-800 self-centerh-fit font-semibold text-xl">{{job}}</p>
            <div class="text-sm">
                <p class="text-green-700 self-centerh-fit">{{category}}</p>
                <p class="text-green-700 self-centerh-fit">{{job.location}}</p>
            </div>
        </div>
        <div class=" text-xs flex flex-col gap-2">
            {% if job.is_done and job.rated %}
                <a class=" border-2 border-gray-300 bg-gray-300 w-full p-2  text-gray-500 block text-center rounded-md transition-all">Already Rated</a>
                {% elif job.is_done %}
                <a href="{% url "rate:rate_user" username=job.employer.username job_id=job.id %}" class="bg-green-600 w-full p-2 hover:bg-green-700 text-white block text-center rounded-md transition-all" >Rate Employer</a>
            {% else %}
                <form action="{% url 'job:apply_job' job.pk %}" method="post">
                    {% csrf_token %}
                    {% if user.is_worker %}
                        {% if applied %}
                            <button type="submit" class=" w-full p-2 bg-gray-600 block text-center rounded-md transition-all" disabled>Application Already Sent</button>
                        {% else %}
                            <button id="apply" type="submit" class="bg-green-600 w-full p-2 text-white block text-center rounded-md transition-all hover:bg-green-700">Apply Now</button>        
                        {% endif %}
                    {% else %}
                        <button type="submit" class=" w-full p-2 bg-gray-600 block text-center rounded-md transition-all" disabled>This Action is Unavailable</button>
                    {% endif %}
                </form>
                <a href="{% url "chat:conversation" job.employer.username%}" class="white border border-green-600 w-full p-2 text-green-600 block text-center rounded-md transition-all hover:bg-green-600 hover:text-white">Message Me</a>
            {% endif %}
                <button id="go-back" class="white bg-red-600 w-full p-2 text-white block text-center rounded-md  transition-all hover:bg-red-700 ">Back</button>
        </div>
    </div>
    <div class="w-full md:w-4/5 h-fit pb-4">
        <div class="w-full border-2 bg-white rounded-sm  rich-text-content px-4 p-4">
            <p class="text-lg text-green-700 pt-2 ">Description<p>
            <p class="px-5">{{job.description | safe}}</p>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        const popup = document.getElementById('popup');

        if (popup) {
            setTimeout(() => {
                $('#popup').addClass('hidden');
            }, 2000);
        }
    });
</script>
{% endblock content %}

System/job/templates/delete_confirmation.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Delete Job Confirmation{% endblock title %}

{% block content %}
<div class="w-full h-full flex p-4 transition-all">
    <div class="bg-white rounded-md h-fit p-4 shadow-md w-auto mx-auto border my-auto">
        <p class="text-xl text-center">Are you sure you want to <span class="font-bold">delete</span> this job?</p>
        <p class="mt-3"><span class="font-medium">Job Title</span>: {{ job.title }}</p>
        
        <form method="post" class=" grid grid-cols-2 grid-rows-1 gap-4 mt-5">
            {% csrf_token %}
            <button type="submit" class="bg-red-600 hover:bg-red-700 text-white rounded p-2">Confirm Delete</button>
            <a href="{% url 'job:edit_job' job.id %}" class=" text-center bg-gray-500 hover:bg-gray-600 text-white h-full rounded p-2">Cancel</a>
        </form>
    </div>
</div>
{% endblock content %}

System/job/templates/edit_job.html
{% extends "layout.html" %}
{% load static %}
{% block custom_head_tag %}
    <script src="{% static "js/job.js" %}"></script>
    <link rel="stylesheet" href="{% static 'css/job.css' %}">
{% endblock custom_head_tag %}

{% block title %}Edit{% endblock title %}

{% block content %}
<div id="custom-popup" class="transition-all backdrop-blur-sm">
    <div class="bg-white p-6 rounded border-2 text-center">
        <p id="popup-message" class="mb-4 text-xl"></p>
        <div class="flex justify-center gap-4">
            <button id="confirm-btn" class="bg-green-500 text-white px-4 py-2 rounded">Confirm</button>
            <button id="cancel-btn" class="bg-red-600 text-white px-4 py-2 rounded">Cancel</button>
        </div>
    </div>
</div>

<a id="discard-changes" href="{% url 'job:my_jobs' job_id=job.id %}" id="discard-btn" class="px-4 bg-red-700 p-2 text-white mt-2 rounded-md hover:bg-red-800 transition-colors sticky  left-5 top-20 ">Back</a>
<div class="flex flex-col items-center w-full p-4">
    <div class="flex flex-col w-11/12 lg:w-3/4 bg-white rounded-md border-2 p-10">
        <p class="text-green-600 text-3xl font-bold text-left mb-2">Edit Job</p> 
        <form method="POST" class="space-y-4">
            {% csrf_token %}
            {{ form.media }}

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
                
                <div class="space-y-6">
                    <div>
                        <label for="title" class="font-semibold">Title</label>
                        {{ form.title }}
                        <small class="text-red-700">{{ form.title.errors }}</small>
                    </div>

                    <div>
                        <label for="location" class="font-semibold">Location</label>
                        {{ form.location }}
                        <small class="text-red-700">{{ form.location.errors }}</small>
                    </div>

                    <div>
                        <label class="font-semibold">Job Specifications</label>
                        <div class="flex flex-wrap gap-4 mt-2">
                            <div class="grid grid-cols-1 lg:grid-cols-2 gap-2">
                            
                                <div class="bg-gray space-y-1.5 p-4 rounded">
                                    <p class="font-semibold text-slate-600">Category</p>
                                    {% for choice in form.category.field.choices %}
                                        <label class="flex items-center">
                                            <input type="radio" name="category" value="{{ choice.0 }}" class="mr-2" {% if form.category.value == choice.0 %}checked{% endif %}> {{ choice.1 }}
                                        </label>
                                    {% endfor %}
                                    <small class="text-red-700">{{ form.category.errors }}</small>
                                </div>

                                <div class="bg-gray space-y-1.5 p-4 rounded">
                                    <p class="font-semibold text-slate-600">Schedule</p>
                                    {% for choice in form.schedule.field.choices %}
                                        <label class="flex items-center">
                                            <input type="radio" name="schedule" value="{{ choice.0 }}" class="mr-2" {% if form.schedule.value == choice.0 %}checked{% endif %}> {{ choice.1 }}
                                        </label>
                                    {% endfor %}
                                    <small class="text-red-700">{{ form.schedule.errors }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="space-y-6">
                    <div>
                        <label for="date" class="font-semibold">Date</label>
                        {{ form.date }}
                        <small class="text-red-700">{{ form.date.errors }}</small>
                    </div>

                    <div>
                        <label for="budget" class="font-semibold">Budget</label>
                        {{ form.budget }}
                        <small class="text-red-700">{{ form.budget.errors }}</small>
                    </div>

                    <div>
                        <label class="font-semibold">Payment Method</label>
                        <div class="flex gap-4 mt-2">
                            {% for choice in form.payment_method.field.choices %}
                                <label class="flex items-center">
                                    <input type="radio" name="payment_method" value="{{ choice.0 }}" class="mr-2" {% if form.payment_method.value == choice.0 %}checked{% endif %}> {{ choice.1 }}
                                </label>
                            {% endfor %}
                            <small class="text-red-700">{{ form.payment_method.errors }}</small>
                        </div>
                    </div>
                    <div>
                        <label for="is_done">Mark Job as Done</label>
                        {{form.is_done}}
                    </div>
                </div>
            </div>

            <div class="w-full flex flex-col">
                <label for="description" class="font-semibold">Job Description</label>
                {{ form.description }}
                <small class="text-red-700">{{ form.description.errors }}</small>
            </div>
            <button id="post" type="submit" class="text-sm w-full py-2 bg-green-600 text-white mt-3 rounded-sm hover:bg-green-700">Save Changes</button>
            <a href="{% url 'job:delete_job' job.id %}" class="text-sm w-full text-center bg-red-700 p-2 text-white inline-block mt-3 rounded-sm hover:bg-red-800">Delete job</a>
        </form>
    </div>
</div>
{% endblock content %}

System/job/templates/job_detail.html
{% extends "layout.html" %}
{% load static %}
{% block custom_head_tag %}
    <script src="{% static "js/job.js" %}"></script>
    {% comment %} <link rel="stylesheet" href="{% static 'css/job.css' %}"> {% endcomment %}
{% endblock custom_head_tag %}

{% block title %}My Jobs{% endblock title %}

{% block content %}
<div id="custom-popup" class="transition-all backdrop-blur-sm">
    <div class="bg-white p-6 rounded border-2 text-center">
        <p id="popup-message" class="mb-4 text-sm"></p>
        <div class="flex justify-center gap-4">
            <button id="confirm-btn" class="bg-green-500 text-white px-4 py-2 rounded w-1/2">Confirm</button>
            <button id="cancel-btn" class="bg-red-600 text-white px-4 py-2 rounded w-1/2">Cancel</button>
        </div>
    </div>
</div>

{% for message in messages %}
    {% if message %}
        <div id="popup" class="fixed h-5/6 w-full flex flex-row transition-all">
            <div class="bg-white w-1/4 mx-auto mt-auto p-4 border-l-4 border-green-600 shadow-custom_spread">
                <p>{{ message }}</p>
            </div>
        </div>
    {% endif %}
{% endfor %}

<div class="w-full p-4 px-2 md:px-20 xl:px-48 flex flex-col md:flex-row gap-5 transition-all">
    <div class=" bg-white rounded-md h-fit grid p-4 border-2 w-full md:w-3/4">
        <div class="text-3xl font-bold text-green-600">{{job.title}}</div>
        <div>
            <a class="text-gray-600 hover:text-green-400 transition-colors" href="{% url "job:edit_job" job_id=job.id %}">Edit Job</a>
        </div>
        {% if job.location %}
            <div class="mt-5">
                <p class="font-medium">Location</p>
                {{job.location|safe}}
            </div>
        {% endif %}
        <div class="mt-5">
            <p class="font-medium">Description</p>
            <div class="rich-text-content font-normal">
                {{job.description|safe}}
            </div>
        </div>
    </div>
    <div class=" bg-white rounded-md h-fit p-4 border-2 w-full md:w-2/3 lg:w-1/3" >
        <div class="text-center w-full text-xl font-bold text-green-600 mb-5">
            Job Applications
        </div>
        {% if applications and owner %}
            {% for application in applications %}
            <div class="border-2 border-green-300 p-5 mt-5 w-full rounded grid">
                <div>
                    <p class="text-sm">Application ID: <strong>{{application.id}}</strong></p>
                    <a class="text-xl font-semibold w-fit hover:text-green-600 transition-all" href="{% url "profile:profile" username=application.worker %}">{{application.worker}}</a>
                </div>
                <p>Status: <span class="font-medium {% if application.status == 'completed' %}text-green-700 {% else %} text-orange-700 {% endif %}">{{application.status}}</span>
                </p>
                <p class="text-sm">{{application.applied_at}}</p>
                    {% if application.status == 'completed' %}
                        {% if application.rated %}    
                            <a class=" bg-gray-300 border-2 border-gray-300 p-2 w-full my-1 rounded-sm text-gray-500 text-center bg-opacity-85 text-sm"> Finished Rating </a>
                            {% else %}
                                <a href="{% url "rate:rate_user" username=application.worker.username job_id=application.job.id %}" class="hover:bg-green-700 bg-green-600 p-2 w-full my-1 rounded-sm text-white text-center text-sm"> Rate User </a>
                        {% endif %}
                    {% elif application.status == 'declined' %}

                    {% elif application.status == 'accepted' %}
                        <button class="bg-orange-400 p-2 w-full mt-1 rounded-sm text-sm text-white" disabled>Job Ongoing</button>
                    {% else %}
                        <form action="{% url 'job:accept' application.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="bg-green-500 p-2 w-full my-1  rounded-sm text-white text-sm">Accept</button>
                        </form>
                        <form action="{% url 'job:reject' application.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="bg-red-600 p-2 w-full mt-1 rounded-sm text-white text-sm">Reject</button>
                        </form>
                {% endif %}
            </div>
            {% endfor %}
            {% else %}
            <p>No applicants applied</p>
        {% endif %}
    </div>
</div>

<script>
    $(document).ready(function() {
        const popup = document.getElementById('popup');

        if (popup) {
            setTimeout(() => {
                $('#popup').addClass('hidden');
            }, 2000);
        }
    });
</script>
{% endblock content %}