System/custom_admin/urls.py
from django.urls import path
from .views import AdminViews

app_name = "custom_admin"
urlpatterns = [
    path('overview/',AdminViews.overview, name="overview"),
    path('users/',AdminViews.user_admin_view, name="users"),
    path('users/edit/<int:user_id>',AdminViews.edit_user_admin_view, name="edit_users"),
    path('jobapplications/',AdminViews.job_application_admin, name="job_applications"),
    path('jobapplications/edit/<int:application_id>',AdminViews.edit_application, name="edit_application"),
    path('jobs/',AdminViews.job_admin, name="job_admin"),
    path('edit_job/<int:job_id>', AdminViews.job_edit, name='edit_job'),
    path('add_user/', AdminViews.add_user, name='add_user'),
]

System/custom_admin/templates/add_user.html
{% load static %}
{% load static tailwind_tags %}
{% load livereload_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/font.css" %}" rel="stylesheet" />
    <link href="{% static 'ckeditor/ckeditor/contents.css' %}" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/custom_admin.css" %}">
    <link rel="stylesheet" href="{% static "css/job.css" %}">
    <script src="{% static "js/admin.js" %}"></script>
    {% tailwind_css %}
    <title>Add User</title>
</head>
<body>
    <div class="w-full flex flex-col items-center py-10">
        <div id="custom-popup" class="transition-all backdrop-blur-sm">
            <div class="bg-white p-6 rounded shadow-lg text-center">
                <p id="popup-message" class="mb-4"></p>
                <div class="flex justify-center gap-4">
                    <button id="confirm-btn" class="w-1/2 bg-green-500 text-white px-6 py-2 rounded">Confirm</button>
                    <button id="cancel-btn" class="w-1/2 bg-red-600 text-white px-6 py-2 rounded">Cancel</button>
                </div>
            </div>
        </div>
        <div class="fixed w-fit left-0 px-10">
            <button id="cancel-changes" class="bg-red-700 py-2 px-5 rounded-md text-white hover:bg-red-600">Go Back</button>
        </div>
        <form method="post" class="form w-2/3 bg-white p-4 border-2 rounded-md flex flex-col" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} 
            <p class="text-xl text-green-800 font-bold">Create User</p>
            <div class="p-0">
                <label for="username">Username</label>
                {{form.username}}
                <span class="text-xs text-red-800">{{form.errors.username.0}}</span>
            </div>
            <div class="flex flex-col gap-0 p-0">
                <label for="username">Password</label>
                {{form.password.0}}
                <div class="p-0 text-red-800 text-xs m-0">{{form.errors.password.0}}</div>
            </div>
            <div class="flex flex-col gap-0 p-0">
                <label for="username">Create a Worker Account</label>
                <div class="flex flex-row justify-start p-0 w-1/5">
                    {{form.is_worker.0}}
                    {{form.is_worker.1}}
                </div>
                <div class="p-0 text-red-800 text-xs m-0">{{form.errors.is_worker.0}}</div>
            </div>
            <div class="flex flex-col gap-0 p-0">
                <label for="username">Create an Admin Account</label>
                <div class="flex flex-row justify-start p-0 w-1/5">
                    <label for="id_is_superuser" class="w-fit">Yes</label>
                    <input type="checkbox" name="id_is_superuser" value="true" class="my-auto">
                </div>
                <div class="p-0 text-red-800 text-xs m-0">{{form.errors.is_superuser.0}}</div>
            </div>
            <button class="mt-4 w-full bg-primary_color text-white py-2 hover:bg-green-700" type="submit">Create User</button>
        </form>
    </div>
</body>
</html>

System/custom_admin/templates/base_admin.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{% static "js/admin.js" %}"></script>
    {% block custom_head_tag %}{% endblock custom_head_tag %}
    {% tailwind_css %}
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="bg-gray-100 h-screen md:p-6 sm:p-8 grid grid-rows-10">
    <div class="bg-white w-full border-2 rounded-md flex flex-row items-center p-5">
        <div class="flex flex-col">
            <p class="text-xl font-bold">{% block name %}{% endblock name %}</p>
            <p class="text-sm">Admin</p>
        </div>
        <ul class="flex flex-row ml-auto gap-4">
            <li><a href="{% url "custom_admin:overview" %}" class="transition {% if 'overview' in request.path %} text-teal-600 hover:text-secondary{% else %}text-gray-700 hover:text-black{% endif %}">Overview</a></li>
            <li><a href="{% url "custom_admin:users" %}" class="transition {% if 'users' in request.path %} text-teal-600 hover:text-secondary{% else %}text-gray-700 hover:shadow-sm{% endif %}">Users</a></li>
            <li><a  href="{% url "custom_admin:job_admin" %}" class="transition {% if 'jobs' in request.path %} text-teal-600 hover:text-secondary{% else %}text-gray-700 hover:text-black{% endif %}">Jobs</a></li>
            <li><a  href="{% url "custom_admin:job_applications" %}" class="transition {% if 'jobapplications' in request.path %} text-teal-600 hover:text-secondary{% else %}text-gray-700 hover:text-black{% endif %}">Job Applications</a></li>
            <li><a href="{% url "login:logout" %}" class="text-red-600 transition hover:text-red-800">Logout</a></li>
        </ul>
    </div>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

System/custom_admin/templates/edit_application.html
{% load static %}
{% load static tailwind_tags %}
{% load livereload_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/font.css" %}" rel="stylesheet" />
    <link href="{% static 'ckeditor/ckeditor/contents.css' %}" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/custom_admin.css" %}">
    <link rel="stylesheet" href="{% static "css/job.css" %}">
    <script src="{% static "js/admin.js" %}"></script>
    {% tailwind_css %}
    <title>Edit {{user}}</title>
</head>
<body>
    <div class="w-full bg-slate-100 flex flex-col items-center py-10 h-screen justify-center">
        <div id="custom-popup" class="transition-all backdrop-blur-sm">
            <div class="bg-white p-6 rounded border-2 text-center">
                <p id="popup-message" class="mb-4 text-sm"></p>
                <div class="flex justify-center gap-4">
                    <button id="confirm-btn" class="bg-green-500 text-white px-6 py-2 rounded">Confirm</button>
                    <button id="cancel-btn" class="bg-red-600 text-white px-6 py-2 rounded">Cancel</button>
                </div>
            </div>
        </div>
        <div class="fixed w-fit left-0 top-10 px-10">
            <button id="cancel-changes" class="bg-red-700 py-2 px-5 rounded-md text-white hover:bg-red-600">Go Back</button>
        </div>
        <form method="post" class="form w-2/3 bg-white p-10 shadow-custom_spread rounded-md">
            {% csrf_token %}
            {{ form.media }} 
            {{form.as_p}}
            <div class="w-full p-2">
                <button class="w-full bg-primary_color text-white hover:bg-green-700 mt-6" type="submit">Confirm Changes</button>
            </div>
        </form>
    </div>
</body>
</html>

System/custom_admin/templates/edit_job_admin.html
{% load static %}
{% load static tailwind_tags %}
{% load livereload_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/font.css" %}" rel="stylesheet" />
    <link href="{% static 'ckeditor/ckeditor/contents.css' %}" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "css/custom_admin.css" %}">
    <link rel="stylesheet" href="{% static "css/job.css" %}">
    <script src="{% static "js/admin.js" %}"></script>
    {% tailwind_css %}
    <title>Edit {{user}}</title>
</head>
<body>
    <div class="w-full flex flex-col items-center py-10">
        <div id="custom-popup" class="transition-all backdrop-blur-sm">
            <div class="bg-white p-6 rounded shadow-lg text-center">
                <p id="popup-message" class="mb-4"></p>
                <div class="flex justify-center gap-4">
                    <button id="confirm-btn" class="w-1/2 bg-green-500 text-white px-6 py-2 rounded">Confirm</button>
                    <button id="cancel-btn" class="w-1/2 bg-red-600 text-white px-6 py-2 rounded">Cancel</button>
                </div>
            </div>
        </div>
        
        <div class="fixed w-fit left-0 px-10">
            <button id="cancel-changes" class="bg-red-700 py-2 px-5 rounded-md text-white hover:bg-red-600">Go Back</button>
        </div>

        <form method="post" class="form w-2/3 bg-white p-10 border-2 rounded-md" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} 
            <div>
                <label for="title">Title</label>
                {{form.title}}
                <span class="text-xs text-red-700">{{form.errors.title}}</span>
            </div>
            <div>
                <label for="title">Location</label>
                {{form.location}}
                <span class="text-xs text-red-700">{{form.errors.location}}</span>
            </div>
            
            <div>
                <label for="title">Description</label>
                {{form.description | safe}}
                <span class="text-xs text-red-700">{{form.errors.description}}</span>
            </div>
            
            <div>
                <label for="title">Date</label>
                {{form.date | safe}}
                <span class="text-xs text-red-700">{{form.errors.date}}</span>  
            </div>

            <div>
                <label for="title">Budget</label>
                {{form.budget}}
                <span class="text-xs text-red-700">{{form.errors.budget}}</span>    
            </div>
            <div class="flex flex-row h-fit">
                <div>
                    <label for="title" class="text-medium">Category</label>
                    <div class="flex flex-col">
                        {% for field in form.category %}
                            {{field}}
                        {% endfor %}
                    </div>
                    <span class="text-xs text-red-700">{{form.errors.category}}</span>
                </div>
                <div>
                    <label for="title">Schedule</label>
                    <div class="flex flex-col">
                        {% for field in form.schedule %}
                            {{field}}
                        {% endfor %}
                    </div>
                    <span class="text-xs text-red-700">{{form.errors.schedule}}</span>
                </div>
                <div>
                    <label for="title">Payment Method</label>
                    <div class="flex flex-col">
                        {% for field in form.payment_method %}
                            {{field}}
                        {% endfor %}
                    </div>
                    <span class="text-xs text-red-700">{{form.errors.payment_method}}</span>
                </div>
                
                <div>
                    <label for="title">Mark as Completed</label>
                    {{form.is_done}}
                </div>
            </div>
            <button class="w-full bg-primary_color text-white py-2 hover:bg-green-700" type="submit">Confirm Changes</button>
        </form>
    </div>
</body>
</html>

System/custom_admin/templates/job_admin.html
{% extends "base_admin.html" %}
{% load static %}
{% block custom_head_tag %}
    <script src="{% static "js/job_admin.js" %}"></script>
{% endblock custom_head_tag %}
{% block title %}Job{% endblock title %}

{% block name %}{{request.user}}{% endblock name %}

{% block content %}
    <div class="w-full h-fit py-5">
        <h3 class="text-2xl font-bold">Job</h3>
        <div class="w-full flex flex-row gap-5">
            <div class="w-1/4 border-2 bg-white p-4 flex flex-row justify-center gap-4" >
                <img class="h-16 self-center" src="{% static "images/postadd.svg" %}" alt="">
                <div class="my-auto">
                    <p class="font-medium text-gray-500 text-xs">Jobs Posted</p>
                    {% if job_summary.job_posted %}
                        <h1 class="text-4xl font-bold">{{job_summary.job_posted}}</h1>
                    {% endif %}
                </div>
            </div>
            <div class="w-1/4 border-2 bg-white p-4 flex flex-center justify-center gap-4">
                <img class="h-16 self-center" src="{% static "images/activejob.svg" %}" alt="">
                <div class="my-auto">
                    <p class="font-medium  text-gray-500 text-xs">Active</p>
                    <h1 class="text-4xl font-bold ">
                        {% if job_summary.active %}
                            {{job_summary.active}}
                        {% else %}
                            0
                        {% endif %}
                    </h1>
                </div>
            </div>
            <div class="w-1/4 border-2 bg-white p-4 flex flex-row justify-center gap-4">
                <img class="h-16 self-center" src="{% static "images/finished.svg" %}" alt="">
                <div class="my-auto">
                    <p class="font-medium  text-gray-500 text-xs">Completed</p>
                    {% if job_summary.completed %}    
                        <h1 class="text-4xl font-bold ">{{job_summary.completed}}</h1>
                    {% endif %}
                </div>
            </div>
            <div class="w-1/4 border-2 bg-white p-4 flex flex-row justify-center gap-4">
                <img class="h-16 self-center" src="{% static "images/money.svg" %}" alt="">
                <div class="my-auto">
                    <p class="font-medium  text-gray-500 text-xs">Revenue</p>
                    {% if job_summary.revenue %}
                        <h1 class="text-4xl font-bold ">₱{{job_summary.revenue}}</h1>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="w-full flex flex-row gap-4 py-4 ">
            <div class="max-w-full bg-white border-2 w-3/4">
                <canvas id="job-created" class="w-full max-h-80"></canvas>
            </div>
            <div class="max-w-full bg-white border-2 w-2/3">
                <canvas id="job-tags" class="w-full max-h-80"></canvas>
            </div>
        </div>
        <div class="py-4 px-5 flex flex-row bg-white border-2">
            <form id="sort-form" class="ml-auto"method="get" action="{% url 'custom_admin:job_admin' %}">
                <label for="sort_option" class="text-xs">Order by:</label>
                <select name="sort_option" id="sort_option" class="text-xs" style="font-size: 0.75rem;">
                    <option value="title" {% if current_sort_option == "title" %}selected{% endif %}>title</option>
                    <option value="employer" {% if current_sort_option == "employer" %}selected{% endif %}>employer</option>
                    <option value="tag" {% if current_sort_option == "tag" %}selected{% endif %}>tag</option>
                    <option value="created_at" {% if current_sort_option == "created_at" %}selected{% endif %}>created at</option>
                    <option value="budget" {% if current_sort_option == "budget" %}selected{% endif %}>budget</option>
                    <option value="location" {% if current_sort_option == "location" %}selected{% endif %}>location</option>
                </select>
                <label for="sort_by" class="text-xs">Sort</label>
                <select name="sort_by" id="sort_by" class="text-xs" style="font-size: 0.75rem;">
                    <option value="-" {% if sort_by == "-" %}selected{% endif %}>Descending</option>
                    <option value="" {% if sort_by == "" %}selected{% endif %}>Ascending</option>
                </select>
            </form>
        </div>
        <table class="table-auto w-full rounded-md border border-slate-300">
            <thead>
                <tr class="border-b bg-slate-200 text-center">
                    <th class="py-2 text-gray-600 font-semibold text-sm">Job</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Employer</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Tags</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Created Date</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Budget</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Location</th>
                    <th class="py-2 text-gray-600 font-semibold text-sm">Status</th>
                </tr>
            </thead>
            <tbody class="text-sm">
                {% for job in  jobs %}
                    <tr>
                        <td class="py-2 px-6 border"><a href="{% url 'custom_admin:edit_job' job_id=job.id %}" class="hover:text-secondary">{{job}}</a></td>
                        <td class="py-2 px-6 border"><a href="{% url 'profile:profile' username=job.employer %} " class="hover:text-secondary">{{job.employer}}</a></td>
                        <td class="py-2 px-6 border">{{job.category}}</td>
                        <td class="py-2 px-6 border">{{job.created_at}}</td>
                        <td class="py-2 px-6 border">{{job.budget}}</td>
                        <td class="py-2 px-6 border">{{job.location}}</td>
                        {% if job.finished_at %}
                            <td class="py-2 px-6 border text-green-600">Completed</td>
                        {% else %}
                            <td class="py-2 px-6 border text-orange-700">Active</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script type="application/json" id="job-date">{{ job_date|safe }}</script>
    <script type="application/json" id="job-count">{{ job_count|safe }}</script>
    <script type="application/json" id="label">{{ tag.label|safe }}</script>
    <script type="application/json" id="count">{{ tag.count|safe }}</script>
    
{% endblock content %}

System/custom_admin/templates/job_application_admin.html
{% extends "base_admin.html" %}
{% load static %}
{% block custom_head_tag %}
<script src="{% static "js/user_charts.js" %}"></script>
{% endblock custom_head_tag %}
{% block title %}Job Application{% endblock title %}

{% block name %}{{request.user}}{% endblock name %}

{% block content %}
    <div class="w-full h-fit mt-5 rounded-md p-4">
        <h3 class="text-2xl font-medium">Job Application</h3>
        <div class="flex flex-row gap-4 w-full">
            <div  class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="self-center h-16" src="{% static "images/submitted.svg" %}" alt="">
                <div>
                    <p class="font-medium text-gray-500 text-xs">Applications Submitted</p>
                    <h1 class="text-4xl font-bold ">{{application_overview.total_applications}}</h1>
                </div>
            </div>
            <div  class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="self-center h-16" src="{% static "images/pending.svg" %}" alt="">
                <div>
                    <p class="font-medium text-gray-500 text-xs">Pending Applications</p>
                    <h1 class="text-4xl font-bold ">{{application_overview.total_pending_applications}}</h1>
                </div>    
            </div>
            <div  class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="self-center h-16" src="{% static "images/accepted.svg" %}" alt="">
                <div>
                    <p class="font-medium text-gray-500 text-xs">Accepted Applications</p>
                    <h1 class="text-4xl font-bold ">{{application_overview.total_accepted_applications}}</h1>
                </div>
            </div>
            <div class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="self-center h-16" src="{% static "images/finished.svg" %}" alt="">
                <div>
                    <p class="font-medium text-gray-500 text-xs">Finished Applications</p>
                    <h1 class="text-4xl font-bold ">{{application_overview.total_completed}}</h1>
                </div>
            </div>
        </div>
        <div class="py-4">
            <table class="table-auto w-full rounded-md border bg-gray-200">
                <thead>
                    <tr class="border-b bg-slate-100 text-center">
                        <th class="py-2 text-gray-600 font-semibold text-sm border">Job Application</th>
                        <th class="py-2 text-gray-600 font-semibold text-sm border">Job</th>
                        <th class="py-2 text-gray-600 font-semibold text-sm border">Worker Name</th>
                        <th class="py-2 text-gray-600 font-semibold text-sm border">Application Status</th>
                        <th class="py-2 text-gray-600 font-semibold text-sm border">Date Applied</th>
                    </tr>
                </thead>
                <tbody class="text-sm">
                    {% for application in  applications %}
                        <tr class="bg-white">
                            <td class="py-2 px-6 border"><a href="{% url 'custom_admin:edit_application' application_id=application.id %}" class="hover:text-secondary">{{application}}</a></td>
                            <td class="py-2 px-6 border">{{application.job}}</td>
                            <td class="py-2 px-6 border">{{application.worker}}</td>
                            <td class="py-2 px-6 border 
                            {% if application.status|lower == 'declined' %}
                                text-red-600
                            {% elif application.status|lower == 'accepted' %}
                                text-green-600
                            {% elif application.status|lower == 'completed' %}
                                text-blue-600
                            {% else %}
                                text-orange-500
                            {% endif %}">{{application.status}}</td>
                            <td class="py-2 px-6 border">{{application.applied_at}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

System/custom_admin/templates/user_admin.html
{% extends "base_admin.html" %}
{% load static %}
{% block custom_head_tag %}
<script src="{% static "js/user_charts.js" %}"></script>
{% endblock custom_head_tag %}
{% block title %}Users{% endblock title %}

{% block name %}{{request.user}}{% endblock name %}

{% block content %}
    <div class="w-full rounded-md mt-5">
        <h3 class="text-2xl font-bold">Users</h3>
        <div class="flex flex-row gap-4">
            <div class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">            
                <img class="h-16 self-center " src="{% static "images/register.svg" %}" alt="">
                <div class="my-auto">
                    <p class=" text-gray-500 text-xs">Number of Registered Users</p>
                    <p class=" text-4xl font-bold">{{total_users}}</p>
                </div>
            </div>
            <div class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="h-16 self-center" src="{% static "images/actove.svg" %}" alt="">
                <div class="my-auto">
                    <p class=" text-gray-500 text-xs">Number of Active Users</p>
                    <p class=" text-4xl font-bold">{{active_users_count}}</p>
                </div>
            </div>
            <div class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="h-16 self-center" src="{% static "images/worker.svg" %}" alt="">
                <div class="my-auto">
                    <p class=" text-gray-500 text-xs">Number of Workers</p>
                    <p class=" text-4xl font-bold">{{worker_count}}</p>
                </div>
            </div>
            <div class="flex flex-row justify-center bg-white border-2 p-4 w-1/4 gap-4">
                <img class="h-16 self-center" src="{% static "images/employer.svg" %}" alt="">
                <div class="my-auto">
                    <p class=" text-gray-500 text-xs">Number of Employers</p>
                    <p class="text-4xl font-bold">{{employer_count}}</p>
                </div>
            </div>
        </div>
        <div class="py-2 px-5 flex flex-row bg-white mt-4 border-2 p-4">
            <div class="my-auto text-xs">
                <a href="{% url 'custom_admin:add_user' %}" class="hover:text-secondary">+ Add User</a>
            </div>
            <form id="sort-form" class="ml-auto"method="get" action="{% url 'custom_admin:users' %}">
                <label for="sort_option" class="text-xs">Order by:</label>
                <select name="sort_option" id="sort_option" class="text-xs px-1 w-fit">
                    <option value="">Select</option>
                    <option value="is_worker" {% if current_sort_option == "is_worker" %}selected{% endif %}>is worker</option>
                    <option value="date_joined" {% if current_sort_option == "date_joined" %}selected{% endif %}>date joined</option>
                    <option value="jobs_applied_count" {% if current_sort_option == "jobs_applied_count" %}selected{% endif %}>jobs applied</option>
                    <option value="jobs_created_count" {% if current_sort_option == "jobs_created_count" %}selected{% endif %}>jobs created</option>
                    <option value="accepted_jobs_count" {% if current_sort_option == "accepted_jobs_count" %}selected{% endif %}>accepted jobs</option>
                </select>
                <label for="sort_by" class="text-xs">Sort</label>
                <select name="sort_by" id="sort_by" class="text-xs px-1 rounded-sm">
                    <option value="-" {% if sort_by == "-" %}selected{% endif %}>Descending</option>
                    <option value="" {% if sort_by == "" %}selected{% endif %}>Ascending</option>
                </select>
            </form>
        </div>
        <table class="table-auto w-full rounded-md border-2">
            <thead>
                <tr class="border-b bg-gray-200">
                    <th class="py-3 px-6 text-gray-600 font-semibold">Username</th>
                    <th class="py-3 px-6 text-gray-600 font-semibold">Is Worker</th>
                    <th class="py-3 px-6 text-gray-600 font-semibold">Date Joined</th>
                    <th class="py-3 px-6 text-gray-600 font-semibold">Jobs Applied</th>
                    <th class="py-3 px-6 text-gray-600 font-semibold">Jobs Created</th>
                    <th class="py-3 px-6 text-gray-600 font-semibold">Accepted Jobs</th>
                </tr>
            </thead>
            <tbody class="text-sm">
                {% for user in users %}
                    <tr class="border-b  text-center bg-white">
                        <td class="py-3"><a class="hover:text-secondary" href="{% url 'custom_admin:edit_users' user_id=user.id %}">{{user.username}}</a></td>
                        <td>{{user.is_worker}}</td>
                        <td>{{user.date_joined}}</td>
                        <td>{{user.jobs_applied_count}}</td>
                        <td>{{user.jobs_created_count}}</td>
                        <td>{{user.accepted_jobs_count}}</td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
        <script type="application/json" id="user-date">{{ dates|safe }}</script>
        <script type="application/json" id="user-count">{{ counts|safe }}</script>
        <script type="application/json" id="workers">{{ worker_count|safe }}</script>
        <script type="application/json" id="employers">{{ employer_count|safe }}</script>
        
    </div>
{% endblock content %}