System/System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customadmin/', include('custom_admin.urls', namespace="custom_admin")),
    path('register/',include('register.urls', namespace="register")),
    path('login/',include('login.urls', namespace="login")),
    path('', include('landing.urls', namespace="landing")),
    path('profile/', include('profile.urls', namespace='profile')),
    path('employee/', include('employee.urls', namespace="employee")),
    path('employer/', include('employer.urls', namespace="employer")),
    path('job/', include('job.urls', namespace='job')),
    path('chat/', include('chat.urls', namespace="chat")),
    path('rate/', include('rate.urls', namespace='rate'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

System/chat/urls.py
from django.urls import path
from .views import *

app_name="chat"

urlpatterns = [
    path('', chat_index, name='chat_index'),
    path('<str:username>', chat_conversation, name='conversation'),
]

System/job/urls.py
from django.urls import path
from .views import JobViews 

app_name="job"

urlpatterns = [
    path('', JobViews.add_job,name='add_job'),
    path('apply/<int:job_id>', JobViews.apply_job,name='apply_job'),
    path('jobs/<int:job_id>', JobViews.show_applications,name='my_jobs'),
    path('edit/<int:job_id>', JobViews.edit_job,name='edit_job'),
    path('accept/<int:application_id>', JobViews.accept_application,name='accept'),
    path('reject/<int:application_id>/', JobViews.reject_application, name='reject'),
    path('delete/<int:job_id>/', JobViews.delete_job, name='delete_job'),
]

System/templates/access_errors.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/font.css' %}">
    {% tailwind_css %}
    <title>request {{status}}</title>
</head>
<body class="flex flex-row h-screen">
    <div class=" mx-auto my-auto flex flex-col gap-5">
        <span class="h-fit my-auto font-bold text-center text-7xl text-green-800">{{status}}</span>
        <span class="text-xl h-fit my-auto border-t-green-800">
            {% if message %}
                {{message}}
            {% endif %}
        </span>
    </div>
</body>
</html>

System/templates/layout.html
<!DOCTYPE html>
{% load static %}
{% load static tailwind_tags %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/override.css' %}">
  <link rel="stylesheet" href="{% static 'css/font.css' %}">
  <link rel="stylesheet" href="{% static 'css/job.css' %}">
  <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
  {% comment %} <script src="{% static "js/animation.js" %}"></script> {% endcomment %}
  {% tailwind_css %}
  {% block custom_head_tag %}{% endblock custom_head_tag %}
  <title>
    {% block title %}App name{% endblock %}
  </title>
</head>
<body class="overflow-x-hidden h-screen bg-gray-100">
  <nav class="sticky w-full top-0 z-50 bg-white border-b-2 border-b-green-700 py-2 px-2  md:px-20 lg:px-32 xl:px-48 2xl:px-52">
    <div class="flex justify-between items-center">
      <div class="logo self-center">
        <a href="#index">  
          <img class="h-5" src="{% static 'images/Serviso.png' %}" alt="Serviso Logo">
        </a>
      </div>
        {% if user.is_authenticated %}
          <ul class="hidden space-x-6 md:flex">
            <li class="self-center">
              <a class="hover:text-green-600 {% if home %}text-cyan-800 underline{% endif %}" href="{% url "landing:landing_page" %}">Home</a>
            </li>
            <li class="self-center">
            {% if user.is_worker %}
              <a class="hover:text-green-600 {% if 'feed' in request.path %} text-cyan-800 underline{% endif %}" href="{% url 'employee:employee_feed' %}">Worker Feed</a>
            {% else %}
              <a class="hover:text-green-600 {% if 'feed' in request.path %} text-cyan-800 underline{% endif %} " href="{% url 'employer:employer_feed' %}">User Feed</a>
            {% endif %}
            </li>
            <li class="self-center">
              <a class="hover:text-green-600 {% if 'chat' in request.path %} text-cyan-800 underline{% endif %}" href="{% url "chat:chat_index" %}">Chat</a>
            </li>
            <li class="self-center">
              <a class="hover:text-green-600 {% if 'profile' in request.path %} text-cyan-800 underline{% endif %}" href="{% url 'profile:profile' username=request.user.username %}">Profile</a>
            </li>
            <li class="self-center">
              <form method="POST" action="{% url 'login:logout' %}" class="">
                {% csrf_token %}
                <button type="submit" class="bg-red-600 text-white px-4 py-2 rounded hover:bg-red-700">Logout</button>
              </form>
          </li>
          </ul>
        {% else %}
        <ul class="hidden sm:flex space-x-6 py-2">
          <li><a class="hover:text-green-600" href="#explore">Explore</a></li>
          <li><a class="hover:text-green-600" href="#about">About</a></li>
          <li><a class="hover:text-green-600" href="{% url 'login:login' %}">Sign In</a></li>
          <li><a class="join-button bg-green-600 text-white px-4 py-2 rounded hover:bg-blue-600" href="{% url 'register:register' %}">Join</a></li>
        </ul>
        <select class="sm:hidden" name="" id=""  onchange="window.location.href=this.value;">
          <option value="#explore"><a class="hover:text-green-600" href="#explore">Explore</a></option>
          <option value="#about"><a class="hover:text-green-600" href="#about">About</a></option>
          <option value="{% url 'login:login' %}"><a class="hover:text-green-600" href="{% url 'login:login' %}">Sign In</a></option>
          <option value="{% url 'register:register' %}"><a class="join-button bg-green-600 text-white px-4 py-2 rounded hover:bg-blue-600" href="{% url 'register:register' %}">Join</a></option>
        </select>
        {% endif %}
    </div>
  </nav>

  <main class="pt-0 h-5/6">
    {% block content %}

    {% endblock %}
  </main>

</body>
</html>